config/routes.rb
Rails.application.routes.draw do
  root to: "users#index"
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :users ,only: [:show ,:update]
  resources :posts
  resources :follows
  resources :likes
  resources :comments
  resources :requests

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
belongs_to :follower , foreign_key: "follower_id", class_name: "User"
belongs_to :post

end

app/models/follow.rb
class Follow < ApplicationRecord
  belongs_to :user
  belongs_to :following, foreign_key: "followee_id", class_name: "User"
  after_save :destroy_request



  private

  def destroy_request
    req = Request.find(self.request_id)
    req.destroy
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :likes
  has_many :comments

  has_one_attached :post_img


  validates :content, presence: true ,length: { minimum: 5, maximum: 255 }
  validates :caption, presence: true ,length: { minimum: 1, maximum: 100 }

end

app/models/request.rb
class Request < ApplicationRecord
belongs_to :from , class_name: "User"
belongs_to :to , class_name: "User"

end

app/models/user.rb
class User < ApplicationRecord
  #User.follows //followings
  has_many :follows, foreign_key: "user_id"
  #User.followers // followers
  has_many :followers, foreign_key: "followee_id", class_name: "Follow"

  has_many :posts

  has_many :likes , foreign_key: "follower_id"
  has_many :comments , foreign_key: "follower_id"
  has_one_attached :profile_pic

  has_many :sent_requests , foreign_key: "from_id", class_name: "Request"

  has_many :recived_requests, foreign_key: "to_id", class_name: "Request"

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  devise :omniauthable, omniauth_providers: %i[google_oauth2]
  validates :username, presence: true ,length: { minimum: 3, maximum: 25 } , uniqueness: true


  after_create :send_mail


  def self.from_omniauth(access_token)
    data = access_token.info
    user = User.where(email: data['email']).first

    # Uncomment the section below if you want users to be created if they don't exist
    # unless user
    #     user = User.create(name: data['name'],
    #        email: data['email'],
    #        password: Devise.friendly_token[0,20]
    #     )
    # end
    user
end


private

  def send_mail
    UserMailer.welcome_user_mail(self).deliver_later
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:username,:dob,:about])
  end


    
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def index

  end

  def create
    comment = Comment.new(comment_params)
    if comment.save
      redirect_to posts_path
    #else
    #  render :create, status: :unprocessable_entity
    end

  end

  def show
    @comments = Comment.where(post_id: params[:id])

  end



  private
  def comment_params
    params.require(:comment).permit(:comment_text,:follower_id,:post_id)
  end

end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController

  def create
    @follow = Follow.new(user_id: current_user.id,followee_id: follow_params[:followee_id],request_id: follow_params[:request_id])
    if @follow.save
      redirect_to root_path
    end
  end

  def show

  end

  def destroy
    # @follow = Follow.find(params[:id])
    # @follow.destroy
  end


  private

  def follow_params
    params.require(:follow).permit(:followee_id,:request_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def create
    @like = Like.new(likes_params)
    if @like.save
      redirect_to posts_path
    else
    end
  end

  private
  def likes_params
    params.require(:like).permit(:follower_id, :post_id)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index

    @user = User.includes(follows: { following: [:posts, :likes, :comments] }).find(current_user.id)
    @my_posts = Post.where(user_id: current_user.id)

    # @posts = @user.follows.map do |follow|
    #   follow.following.posts
    # end

    # @posts.each do |post|
    #    @post = Post.includes(:likes,:comments).find(post.id)
    # end

    @like = Like.new
    @comment = Comment.new

    # @posts = User.joins(:posts).select('users.*, posts.*') #selects all the field from both the table
    # @likes = Like.where("follower_id = #{current_user.id}").select(:post_id)
    # @likeds = []
    # @likes.each do |like|
    #   @likeds.push(like.post_id)
    # end




  end

  def new
    @post = Post.new

  end

  def create

    @post = Post.new(post_params)
    if @post.save
      redirect_to posts_path
    else
      render :new, status: :unprocessable_entity
    end

  end



private
def post_params
  params.require(:post).permit(:user_id,:content,:caption,:post_img)
end


end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController



  def create
    @request = Request.new(from_id: current_user.id,to_id: params[:to])
    if @request.save
      flash[:notice] = "Request Sent Successfully"
      redirect_to root_path
    end
  end

  def destroy
    @request = Request.find(params[:id])
    @request.destroy
    flash[:notice] = "Request Rejected"



  end




end

app/controllers/users/omniauth_callbacks_controller.rb
# app/controllers/users/omniauth_callbacks_controller.rb:
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env['omniauth.auth'])

      if @user.persisted?
        flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
        sign_in_and_redirect @user, event: :authentication
      else
        session['devise.google_data'] = request.env['omniauth.auth'].except('extra') # Removing extra as it can overflow some session stores
        redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
      end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
def index
  @users = User.all.where("id != ?", current_user.id)
  #returns all the users who are being followed by the current_user

  @followings = current_user.follows.pluck(:followee_id)
  @pendings = current_user.sent_requests.pluck(:id)
  @follow_requests = User.includes(:recived_requests).find(current_user.id)

  @request = Request.new
  @follow = Follow.new


  #@followers = []
  # + implent click on following to unfollow
  # + implement follow back
  # + implement if both are following
end


def show
  @user = User.find(user_params[:id])
end


def update
  user = User.find_by(id: user_params[:id])
  user.profile_pic.attach(pic_params[:profile_pic])
  redirect_to user
end



private
def user_params
  params.permit(:id)
end

private
def pic_params
  params.require(:user).permit(:profile_pic)
end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/show.html.erb
<%= link_to "Go Back" , :back%>

<ul>
    <% @comments.each do |comment|%>
    <li>Username <%= comment.follower.username%></li>
    <li><%= comment.comment_text%></li>
    <br>
    <%end%>

</ul>

app/views/posts/index.html.erb
<%= link_to "Users", root_path %> <br>
<%= link_to "Create a Post", new_post_path %>
<ul>
  <% @user.follows.includes(following: [:posts, :likes, comments: :follower]).each do |follow| %>
    <% follow.following.posts.includes(:likes, :comments).each do |post| %>
      <li>
        <%= post.content %>
      </li>

      <li>
        <%= post.caption %>
      </li>

      <% follower_ids = post.likes.pluck(:follower_id) %>

      <% if follower_ids.include?(current_user.id) %>
        <%= button_to "Liked", @like, :disabled => true %>
      <% else %>
        <%= button_to "Like", @like, data: { disable_with: "Liked" }, params: { like: { post_id: post.id, follower_id: current_user.id } } %>
      <% end %>

      <%= form_with model: @comment do |form| %>
        <%= form.hidden_field :follower_id, value: current_user.id %>
        <%= form.hidden_field :post_id, value: post.id %>
        <%= form.label :comment_text, "Comment:" %>
        <%= form.text_field :comment_text %>
        <%= form.submit "Submit" %>
      <% end %>

      <% comments = post.comments.last(5) %>
      <% comments.each do |comment| %>
        <%= comment.comment_text %>
      <% end %>
      <%= link_to "see more", comment_path(post.id) %>
      <br>
      <br>
    <% end %>
  <% end %>
</ul>
<br>
<br>

    <% @my_posts.each do |post| %>
      <li><%= current_user.username %></li>
      <li><%= post.content %></li>
      <li><%= post.caption%></li>
      <% if post.post_img.attached? %>
      <div class="post-pic">
          <%= image_tag post.post_img, width: "300px" , height: "300px"  %>
      </div>
      <% end %>
    <% end %>


<ul>
  <% @user.follows.each do |follow|%>
    <% follow.following.posts.each do |post|%>

    <li>
        <%= follow.following.username %>
    </li>
    <li>
        <%= post.content %>
    </li>

    <li>
        <%= post.caption%>
    </li>

    <% if post.post_img.attached? %>
    <div class="profile-pic">
        <%= image_tag post.post_img , width: "300px" , height: "300px"  %>
    </div>
    <% end %>
    <br>


    <% follower_ids = post.likes.pluck(:follower_id)%>

    <% if follower_ids.include?(current_user.id)%>
      <%= button_to "Liked", @like , :disabled => true %>
    <%else%>
      <%= button_to "Like", @like , data: { disable_with: "Liked" } , params: { like: { post_id: post.id, follower_id: current_user.id } } %>
    <%end%>


    <%= form_with model:@comment  do |form| %>
      <%= form.hidden_field :follower_id, value: current_user.id %>
      <%= form.hidden_field :post_id, value: post.id %>
      <%= form.label :comment_text, "Comment:" %>
      <%= form.text_field :comment_text %>
      <%= form.submit "Submit" %>
    <% end %>


    <% comments = post.comments.last(5)%>
    <% comments.each do |comment|%>
    <%= comment.comment_text%>
    <%end%>
    <%= link_to "see more" , comment_path(post.id)%>
    <br>
    <br>
  <% end %>
  <% end %>
</ul>

app/views/posts/new.html.erb
<%= form_with model: @post do |form| %>
  <%= form.hidden_field :user_id, value: current_user.id %>
  <%= form.label :content, "content:" %>
  <%= form.text_field :content %>
  <%= form.label :post_img, "Post an Image:" %>
  <%= form.file_field :post_img %>
  <%= form.label :caption, "caption:" %>
  <%= form.text_field :caption %>
  <%= form.submit "Submit" %>

<% end %>

app/views/users/index.html.erb
<h1> Authenticated </h1><br>

<%= link_to "Sign Out", destroy_user_session_path %> <br><br><br>
<%= link_to "See Posts", posts_path %> <br>
<%= link_to "My Profile", user_path(current_user.id)  %> <br>
<br><br>
<% @users.each do |user| %>
   <%= link_to "#{user.name}", user_path(user.id)  %>

   <% if @followings.include?(user.id) %>
   <div>
      <%= button_to "Following",{},:disabled => true %>

      <%# #method 2
      #passssssssss in aaaaaaaaaaaaaa objecttttttttttttt to delete not a new object change the controller
      <%= button_to "Destroy", @follow, method: :delete  %>
      </div>
      <% elsif  @pendings.include?(user.id)%>
      <div>
        <%= button_to "Pending",{},:disabled => true %>

      </div>
    <% else  %>
    <div>
      <%= button_to "Follow", @request , data: { disable_with: "Sent" } , params: { :to => user.id }   %>
    </div>
    <% end %>


<% end %>
<h1>Follow Requests</h1>


  <% @follow_requests.recived_requests.each do |request|%>
    <%=request.from.name%> <br>
    <%= button_to "Accept", @follow , params: { "follow[followee_id]" => request.from.id,"follow[request_id]" => request.id  }   %>
    <%= button_to "Destroy", request, method: :delete  %>
  <%end%>
<%= turbo_frame_tag "test_frame" do %>
  <%= link_to "turbo" , user_path(current_user.id)%>
<% end %>



<br>
<br>
<br>
<br>

app/views/users/show.html.erb
<h1>This is Her</h1>


<%if @user.id == current_user.id %>
    <%= form_with model: @user do |form| %>
        <%= form.file_field :profile_pic %>
        <%= form.submit "Submit" %>
    <%end%>
<% end%>



<% if @user.profile_pic.attached? %>
    <div class="profile-pic">
        <%= image_tag @user.profile_pic , width: "300px" , height: "300px"  %>
    </div>
<% end %>

<%= turbo_frame_tag "test_frame" do %>
    <%= @user.name%><br>
    <%= @user.username%><br>
    <%= @user.dob%><br>
    <%= @user.about%><br>
    <%= @user.email%><br>
<% end %>